#!/bin/bash
# nvidiainfo 1.0.1 - NVIDIA monitor for XFCE genmon plugin
# Copyright (C) 2013 Digirium, see <https://github.com/Digirium/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

gputemp=$(nvidia-settings -q gpucoretemp -t)
usedmem=$(nvidia-settings -q [gpu:0]/UsedDedicatedGPUMemory -t)
clocks2=$(nvidia-settings -q [gpu:0]/GPUCurrentClockFreqsString -t)

nvclock=$(echo $clocks2 | sed 's/nvclock=\([0-9]*\),.*$/\1/')
memclock=$(echo $clocks2 | sed 's/^.*, memclock=\([0-9]*\)$/\1/')

cat <<-EOF
<img>$HOME/.genmon-icon/nvidiainfo.png</img>
<txt>${gputemp}°C ${nvclock}MHz
${usedmem}M ${memclock}MHz</txt>
EOF

exit 0
