#!/bin/bash
# nvidiainfo - NVIDIA monitor for XFCE genmon plugin
# Copyright (C) 2013 Digirium, see <https://github.com/Digirium/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

CF=C
showclock=no
iconfile=$HOME/.genmon-icon/nvidiainfo.png
while getopts ":cFi:v" opt
do
	case $opt in
	c)
		showclock=yes
		;;
	F)
		CF=F
		;;
	i)
		case "$OPTARG" in
		/*)
			iconfile="$OPTARG"
			;;
		*)
			iconfile="$HOME/.genmon-icon/$OPTARG"
			;;
		esac
		;;
	v)
		echo "nvidiainfo 1.0.2 - (C) 2013 Digirium, see <https://github.com/Digirium)"
		echo "Released under the GNU GPL."
		exit 0
		;;
	*)
		echo "Invalid option: -$OPTARG"
		exit 1
		;;
	esac
done

gputemp=$(nvidia-settings -q gpucoretemp -t)
usedmem=$(nvidia-settings -q [gpu:0]/UsedDedicatedGPUMemory -t)

case $CF in
F)
	let "F=($gputemp*9/5)+32"
	gputemp=$F
	;;
esac

case $showclock in
no)
	cat <<-EOF
	<img>$iconfile</img>
	<txt>${gputemp}°$CF
	${usedmem}M</txt>
	EOF
	;;
yes)
	clocks2=$(nvidia-settings -q [gpu:0]/GPUCurrentClockFreqsString -t)
	nvclock=$(echo $clocks2 | sed 's/nvclock=\([0-9]*\),.*$/\1/')
	memclock=$(echo $clocks2 | sed 's/^.*, memclock=\([0-9]*\)$/\1/')

	cat <<-EOF
	<img>$iconfile</img>
	<txt>${gputemp}°$CF ${nvclock}MHz
	${usedmem}M ${memclock}MHz</txt>
	EOF
	;;
esac

exit 0
