#!/bin/bash
# pacinfo - Pacman monitor for XFCE genmon plugin
# Copyright (C) 2013 Digirium, see <https://github.com/Digirium/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

showtxt=no
showaur=no
while getopts ":atv" opt
do
	case $opt in
	a)
		showaur=yes
		;;
	t)
		showtxt=yes
		;;
	v)
		echo "pacinfo 1.0.3 - (C) 2013 Digirium, see <https://github.com/Digirium>"
		echo "Released under the GNU GPL."
		exit 0
		;;
	*)
		echo "Invalid option: -$OPTARG"
		exit 1
		;;
	esac
done

# Default icon is the pacman meaning no packages require
# to be upgraded. Changes to a ghost if updates are found.
iconfile=$HOME/.genmon-icon/pacinfo.png

# Need sudo to be setup so that no password is required. Run pacman
# to update the database and to get package upgrade list. If you use
# AUR packages and have yaourt installed then can show if any AUR
# packages can/will be upgraded too.
case $showaur in
yes)
	yaourt -Sya --noprogressbar &>/dev/null
	pkgs=$(yaourt -Qqua)
	;;
no)
	sudo pacman -Sy --noprogressbar &>/dev/null
	pkgs=$(pacman -Qqu)
	;;

esac

# If there are packages, filter the ignored ones. Add ignored package
# names to the ignorelist line separate names with a bar; wine is put on
# the list as an example, remove it and the bar unless you ignore wine.
t=
let "n=0"
for p in $pkgs
do
	case $p in
	ignorelist|wine)
		;;
	*)
		if [[ -z "$t" ]]
		then
			t="$p"
		else
			t="$t $p"
		fi
		let "n++"
		;;
	esac
done
pkgs="$t"

# Get how many packages are installed.
inst="$(cd /var/lib/pacman/local; ls | wc -l)"

# If there are packages waiting to be upgraded, switch to the
# ghost icon instead of the pacman icon.
if [[ ! -z "$pkgs" ]]
then
	iconfile=$HOME/.genmon-icon/pacinfo-ghost.png
	pkgs="$pkgs (Total: $n)."
	txt1="$n"
else
	pkgs="None."
	txt1="$inst"
fi

# How much disk space is occupied by cached packages?
txt2=$(cd /var/cache/pacman; du -h pkg 2>/dev/null | awk '$2 == "pkg" { print $1 }')

### XFCE GENMON XML ###

echo "<img>$iconfile</img>"

if [[ $showtxt == yes ]]
then

	cat <<-EOF
	<txt>$txt1
	$txt2</txt>
	EOF
fi

cat <<EOF
<tool>Last synchronized: $(date)
EOF

case "$pkgs" in
None.)
	;;
*)
	cat <<-EOF
	Package upgrades waiting: $pkgs
	EOF
	;;
esac

cat <<EOF
Packages installed: $inst
Package cache size: $txt2
Kernel: $(uname -r)
AUR: $showaur</tool>
EOF

exit 0
